export const Actions = {
	DROPBOX_AUTHENTICATION_SUCCESS: 'DROPBOX_AUTHENTICATION_SUCCESS',
	FETCH_AUTHENTICATED_USERS_DOCUMENT_SUCCESS:
		'FETCH_AUTHENTICATED_USERS_DOCUMENT_SUCCESS',
	FETCH_SEARCH_RESULTS_SUCCESS: 'FETCH_SEARCH_RESULTS_SUCCESS',
	RESET_STATE: 'RESET_STATE',
};
